name: 02 - Workflow Events
on: [push, pull_request, workflow_dispatch]

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Show the trigger
        run: echo "Change description to test the 'pull_request' event."